### ISSUE TITLE
"Could not find the template sequence" and "must be real number, not NoneType"

### ISSUE THREAD

**Issue by nduan1** [KosinskiLab/AlphaPulldown#154]
Hi,

I got this error when run"create_individual_features.py", could I have some suggestion?

Thanks!

Ning

"
Alignment will be written to file:'/tmp/tmphrldzh3f/output.a3m'.

Distance Calculation:
^M     100 percent done
Alignment:
^M       0 percent done^M     100 percent done

I0629 10:28:46.277125 23456247932736 utils.py:40] Finished Kalign query in 0.008 seconds
I0629 10:28:46.277712 23456247932736 templates.py:371] Old aligned template: -----------------------------------------------------------KVTKGGPLPFAWDILSHQFMYGSKAYVK-------------------------------------------------------------------------------------------------------------------------------------------------------------
New aligned template: MGHHHHHHGVSKGEEDNMAIIKEFMRFKTHMEGSVNGHEFEIEGEGEGRPYEGTQTAKLKVTKGGPLPFAWDILSHQFX--SKAYVKHPADIPDYLKLSFPEGFKWERVMNFEDGGVVTVTQDSSLQDGEFIYKVKLHGTNFPSDGPVMQKKTMGSEASSERMYPEDGALKGEIKLRLKLKDGGHYDAEVKTTYKAKKPVQLPGAYNANYKLDITSHNEDYTIVEQYERCEGRHSTGGMDELYK
Traceback (most recent call last):
  File "/data/duann2/deeplearning/conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/data/templates.py", line 539, in _extract_template_features
    mmcif_object=mmcif_object)
  File "/data/duann2/deeplearning/conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/data/templates.py", line 294, in _find_template_in_pdb
    mmcif_object.chain_to_seqres))
alphafold.data.templates.SequenceNotInTemplateError: Could not find the template sequence in 5h87_A. Template sequence: KVTKGGPLPFAWDILSHQFMYGSKAYVK, chain_to_seqres: {'A': 'MGHHHHHHGVSKGEEDNMAIIKEFMRFKTHMEGSVNGHEFEIEGEGEGRPYEGTQTAKLKVTKGGPLPFAWDILSHQFXSKAYVKHPADIPDYLKLSFPEGFKWERVMNFEDGGVVTVTQDSSLQDGEFIYKVKLHGTNFPSDGPVMQKKTMGSEASSERMYPEDGALKGEIKLRLKLKDGGHYDAEVKTTYKAKKPVQLPGAYNANYKLDITSHNEDYTIVEQYERCEGRHSTGGMDELYK', 'B': 'MGHHHHHHGVSKGEEDNMAIIKEFMRFKTHMEGSVNGHEFEIEGEGEGRPYEGTQTAKLKVTKGGPLPFAWDILSHQFXSKAYVKHPADIPDYLKLSFPEGFKWERVMNFEDGGVVTVTQDSSLQDGEFIYKVKLHGTNFPSDGPVMQKKTMGSEASSERMYPEDGALKGEIKLRLKLKDGGHYDAEVKTTYKAKKPVQLPGAYNANYKLDITSHNEDYTIVEQYERCEGRHSTGGMDELYK', 'C': 'MGHHHHHHGVSKGEEDNMAIIKEFMRFKTHMEGSVNGHEFEIEGEGEGRPYEGTQTAKLKVTKGGPLPFAWDILSHQFXSKAYVKHPADIPDYLKLSFPEGFKWERVMNFEDGGVVTVTQDSSLQDGEFIYKVKLHGTNFPSDGPVMQKKTMGSEASSERMYPEDGALKGEIKLRLKLKDGGHYDAEVKTTYKAKKPVQLPGAYNANYKLDITSHNEDYTIVEQYERCEGRHSTGGMDELYK', 'D': 'MGHHHHHHGVSKGEEDNMAIIKEFMRFKTHMEGSVNGHEFEIEGEGEGRPYEGTQTAKLKVTKGGPLPFAWDILSHQFXSKAYVKHPADIPDYLKLSFPEGFKWERVMNFEDGGVVTVTQDSSLQDGEFIYKVKLHGTNFPSDGPVMQKKTMGSEASSERMYPEDGALKGEIKLRLKLKDGGHYDAEVKTTYKAKKPVQLPGAYNANYKLDITSHNEDYTIVEQYERCEGRHSTGGMDELYK'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/duann2/deeplearning/conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/data/templates.py", line 762, in _process_single_hit
    kalign_binary_path=kalign_binary_path)
  File "/data/duann2/deeplearning/conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/data/templates.py", line 554, in _extract_template_features
    kalign_binary_path=kalign_binary_path)
  File "/data/duann2/deeplearning/conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/data/templates.py", line 397, in _realign_pdb_template_to_query
    new_template_sequence))
alphafold.data.templates.QueryToTemplateAlignError: Insufficient similarity of the sequence in the database: KVTKGGPLPFAWDILSHQFMYGSKAYVK to the actual sequence in the mmCIF file 5h87_A: MGHHHHHHGVSKGEEDNMAIIKEFMRFKTHMEGSVNGHEFEIEGEGEGRPYEGTQTAKLKVTKGGPLPFAWDILSHQFXSKAYVKHPADIPDYLKLSFPEGFKWERVMNFEDGGVVTVTQDSSLQDGEFIYKVKLHGTNFPSDGPVMQKKTMGSEASSERMYPEDGALKGEIKLRLKLKDGGHYDAEVKTTYKAKKPVQLPGAYNANYKLDITSHNEDYTIVEQYERCEGRHSTGGMDELYK. We require at least 90 % similarity wrt to the shorter of the sequences. This is not a problem unless you think this is a template that should be included.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/duann2/deeplearning/conda/envs/AlphaPulldown/bin/create_individual_features.py", line 247, in <module>
    app.run(main)
  File "/data/duann2/deeplearning/conda/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/data/duann2/deeplearning/conda/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/data/duann2/deeplearning/conda/envs/AlphaPulldown/bin/create_individual_features.py", line 240, in main
    create_and_save_monomer_objects(curr_monomer, pipeline, flags_dict)
  File "/data/duann2/deeplearning/conda/envs/AlphaPulldown/bin/create_individual_features.py", line 204, in create_and_save_monomer_objects
    save_msa=FLAGS.save_msa_files,
  File "/data/duann2/deeplearning/conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphapulldown/objects.py", line 118, in make_features
    input_fasta_path=fasta_file, msa_output_dir=tmpdirname
  File "/data/duann2/deeplearning/conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/data/pipeline.py", line 225, in process
    hits=pdb_template_hits)
  File "/data/duann2/deeplearning/conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/data/templates.py", line 968, in get_templates
    kalign_binary_path=self._kalign_binary_path)
  File "/data/duann2/deeplearning/conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/data/templates.py", line 789, in _process_single_hit
    str(e), parsing_result.errors))
TypeError: must be real number, not NoneType
"

**Comment by dingquanyu** [comment]
Hi,

Sorry but this is a problem with AlphaFold's template search pipeline and maybe you could find similar discussions under AlphaFold's repo? There's also a probability that 5h87_A file was corrupt or damaged in your database directory. 

Yours 
Dingquan

**Comment by jkosinski** [comment]
I think this type of error also appears when one of the software is not installed, could you make sure kalign is installed and also run conda install -c bioconda hmmer hhsuite ?

**Comment by jkosinski** [comment]
Hi @nduan1, just checking to see if this has been resolved?

**Comment by dingquanyu** [comment]
Issue is closed due to inactivity.
