### ISSUE TITLE
Error in the execution of Feature 2

### ISSUE THREAD

**Issue by Resram** [KosinskiLab/AlphaPulldown#165]
Hi, 
  I get the following error while running the feature 2 code snippet.I was wondering if you could spare some time to take a look at the code and error message? Thanks in advance.

(AlphaPulldown) singularity exec \
>     --no-home \
>     --bind /Ap/output:/mnt \
>      alpha-analysis.sif \
>     run_get_good_pae.sh \
>     --output_dir=/mnt \
>     --cutoff=10
I0817 11:26:01.685516 47638540354496 get_good_inter_pae.py:112] now processing P78344_feature_metadata_2023-08-11.txt
I0817 11:26:01.691167 47638540354496 get_good_inter_pae.py:112] now processing models
I0817 11:26:01.696232 47638540354496 get_good_inter_pae.py:112] now processing output.ipynb
I0817 11:26:01.701501 47638540354496 get_good_inter_pae.py:112] now processing O76094.pkl
I0817 11:26:01.706592 47638540354496 get_good_inter_pae.py:112] now processing O76094_feature_metadata_2023-08-10.txt
I0817 11:26:01.711863 47638540354496 get_good_inter_pae.py:112] now processing Q14240_feature_metadata_2023-08-11.txt
I0817 11:26:01.717097 47638540354496 get_good_inter_pae.py:112] now processing Q14240.pkl
I0817 11:26:01.722467 47638540354496 get_good_inter_pae.py:112] now processing P60842_feature_metadata_2023-08-10.txt
I0817 11:26:01.727416 47638540354496 get_good_inter_pae.py:112] now processing P60842.pkl
I0817 11:26:01.732673 47638540354496 get_good_inter_pae.py:112] now processing P78344.pkl
Traceback (most recent call last):
  File "/app/alpha-analysis/get_good_inter_pae.py", line 151, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/app/alpha-analysis/get_good_inter_pae.py", line 141, in main
    pi_score_df=pd.merge(pi_score_df,other_measurements_df,on="jobs")
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 107, in merge
    op = _MergeOperation(
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 700, in __init__
    ) = self._get_merge_keys()
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 1110, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/generic.py", line 1840, in _get_label_or_level_values
    raise KeyError(key)

KeyError: 'jobs'

**Comment by dingquanyu** [comment]
Hi,

It's probably because none of the models has passed your cutoff value. Could you try use a much bigger value for the cutoff e.g. 50? 

Yours
Dingquan

**Comment by Resram** [comment]
Here is the run details with cutoff=50; The error persists.
AlphaPulldown) singularity exec \
>     --no-home \
>     --bind /ibex/scratch/ramakrr/Ap/output:/mnt \
>      alpha-analysis.sif \
>     run_get_good_pae.sh \
>     --output_dir=/mnt \
>     --cutoff=50

I0817 13:13:05.842480 47655807402944 get_good_inter_pae.py:112] now processing P78344_feature_metadata_2023-08-11.txt
I0817 13:13:05.847187 47655807402944 get_good_inter_pae.py:112] now processing models
I0817 13:13:05.851155 47655807402944 get_good_inter_pae.py:112] now processing output.ipynb
I0817 13:13:05.855628 47655807402944 get_good_inter_pae.py:112] now processing O76094.pkl
I0817 13:13:05.859637 47655807402944 get_good_inter_pae.py:112] now processing O76094_feature_metadata_2023-08-10.txt
I0817 13:13:05.863980 47655807402944 get_good_inter_pae.py:112] now processing pi_score_outputs
I0817 13:13:05.867447 47655807402944 get_good_inter_pae.py:112] now processing Q14240_feature_metadata_2023-08-11.txt
I0817 13:13:05.872235 47655807402944 get_good_inter_pae.py:112] now processing Q14240.pkl
I0817 13:13:05.876754 47655807402944 get_good_inter_pae.py:112] now processing P60842_feature_metadata_2023-08-10.txt
I0817 13:13:05.882033 47655807402944 get_good_inter_pae.py:112] now processing P60842.pkl
I0817 13:13:05.886254 47655807402944 get_good_inter_pae.py:112] now processing P78344.pkl
mkdir: cannot create directory ‘/mnt/pi_score_outputs’: File exists
Traceback (most recent call last):
  File "/app/alpha-analysis/get_good_inter_pae.py", line 151, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/app/alpha-analysis/get_good_inter_pae.py", line 141, in main
    pi_score_df=pd.merge(pi_score_df,other_measurements_df,on="jobs")
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 107, in merge
    op = _MergeOperation(
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 700, in __init__
    ) = self._get_merge_keys()
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 1110, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/generic.py", line 1840, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'jobs'

**Comment by dingquanyu** [comment]
It looks like you mounted a wrong directory. Could you try ```--bind /Ap/output:/mnt```

**Comment by Resram** [comment]
Yes, it worked. Thank you prompt response.
