### ISSUE TITLE
'4fxg.cif' is obsliterated at 01-MAR-23 in OBSLTE.dat file, so how to handle the following problem

### ISSUE THREAD

**Issue by liusfore** [KosinskiLab/AlphaPulldown#171]
Traceback (most recent call last):
  File "/mnt/data/anaconda/envs/AlphaPulldown/bin/create_individual_features.py", line 288, in <module>
    app.run(main)
  File "/mnt/data/anaconda/envs/AlphaPulldown/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/mnt/data/anaconda/envs/AlphaPulldown/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/mnt/data/anaconda/envs/AlphaPulldown/bin/create_individual_features.py", line 280, in main
    create_and_save_monomer_objects(curr_monomer, pipeline,
  File "/mnt/data/anaconda/envs/AlphaPulldown/bin/create_individual_features.py", line 223, in create_and_save_monomer_objects
    m.make_mmseq_features(DEFAULT_API_SERVER=DEFAULT_API_SERVER,
  File "/mnt/data/anaconda/envs/AlphaPulldown/lib/python3.8/site-packages/alphapulldown/objects.py", line 250, in make_mmseq_features
    template_features = [self.mk_template(a3m_lines[0],
  File "/mnt/data/anaconda/envs/AlphaPulldown/lib/python3.8/site-packages/alphapulldown/objects.py", line 183, in mk_template
    templates_result = template_featuriser.get_templates(
  File "/mnt/data/anaconda/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/templates.py", line 893, in get_templates
    result = _process_single_hit(
  File "/mnt/data/anaconda/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/templates.py", line 737, in _process_single_hit
    cif_string = _read_file(cif_path)
  File "/mnt/data/anaconda/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/templates.py", line 681, in _read_file
    with open(path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../AlphaLink2/alphafold/all_data/pdb_mmcif/mmcif_files/4fxg.cif'

**Comment by dingquanyu** [comment]
Hi,

Sorry I haven't encountered this type of problem myself. Maybe for now you could download 5JPM.cif and rename it as 4fxg.cif in that directory? I think generally, you might have to update your pdb_mmcif database if you use a newer version of OBSLTE.dat. Perhaps the discussions under AlphaFold's repo will provide you with more information.

Yours
Dingquan
