### ISSUE TITLE
alpha-analysis.sif - no csv output

### ISSUE THREAD

**Issue by JtheBAB** [KosinskiLab/AlphaPulldown#173]
Hi

We are using alpha-analysis.sif to generate the csv output. When we run it with around 10 input files it works. When we use 146 input files we get this:
`
*Writing CSV file with features *
*Calculating PI-score*
/software/pi_score/utils.py:305: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  topredict_1 = sc.transform(topredict_1)
Traceback (most recent call last):
  File "/app/alpha-analysis/get_good_inter_pae.py", line 150, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 308, in run
    run_main(main, args)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 254, in run_main
    sys.exit(main(argv))
  File "/app/alpha-analysis/get_good_inter_pae.py", line 139, in main
    pi_score_df = run_and_summarise_pi_score(FLAGS.output_dir,good_jobs,FLAGS.surface_thres)
  File "/app/alpha-analysis/get_good_inter_pae.py", line 92, in run_and_summarise_pi_score
    filtered_df=pd.merge(filtered_df,pi_score,on='jobs')
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 107, in merge
    op = _MergeOperation(
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 700, in __init
    ) = self._get_merge_keys()
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 1097, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/generic.py", line 1840, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'jobs'
`

Any idea how to fix that?

Thanks

**Comment by dingquanyu** [comment]
Hi,

Would you mind sharing the full command with me? Usually, this happens when none of the models satisfied your cutoff. Could you try increase it to some higher number e.g. 50 or 100?

**Comment by JtheBAB** [comment]
`
apptainer exec --no-home --bind /path/run1:/mnt /path/alpha-analysis.sif run_get_good.sh --output_dir=/mnt --cutoff=15
`

It worked with at least 52 input files.

**Comment by dingquanyu** [comment]
I see. So it's solved?

**Comment by JtheBAB** [comment]
When we split it yes. Just wondering why it happens when it has more input files

**Comment by dingquanyu** [comment]
> When we split it yes. Just wondering why it happens when it has more input files

@jkosinski do we still leave this issue open? I don't see any bugs related to this?

**Comment by jkosinski** [comment]
I think if it still crashes on high number of files, than we should fix it. Do we reproduce this error on high number of input files?

**Comment by DimaMolod** [comment]
Fix in 829f0f8784b386cc423182908535dc3717bbbd2c and 67d25514f507098114b88e83e995fe4148b13e1b and d0e4392f6893e2114234af5e3ea3e99c39967596
