### ISSUE TITLE
Error: kalign failed

### ISSUE THREAD

**Issue by th-of** [KosinskiLab/AlphaPulldown#180]
I keep running into the same error and crash when using the same input sequences. Any suggestions?

W0915 22:28:07.680782 140600048301888 templates.py:547] The exact sequence LPFTGLNTPNGV was not found in 7zcj_A. Realigning the template to the actual sequence.
I0915 22:28:07.680937 140600048301888 kalign.py:66] Aligning 2 sequences
I0915 22:28:07.681179 140600048301888 kalign.py:87] Launching subprocess "/home/thomas-ws/miniconda3/envs/AlphaPulldown/bin/kalign -i /tmp/tmpiwf7cwwu/input.fasta -o /tmp/tmpiwf7cwwu/output.a3m -format fasta"
I0915 22:28:07.767620 140600048301888 utils.py:36] Started Kalign query
I0915 22:29:01.454128 140600048301888 kalign.py:94] Kalign stdout:

stderr:

Kalign version 2.04, Copyright (C) 2004, 2005, 2006 Timo Lassmann

        Kalign is free software. You can redistribute it and/or modify
        it under the terms of the GNU General Public License as
        published by the Free Software Foundation.

reading from STDIN: 

I0915 22:29:01.454264 140600048301888 utils.py:40] Finished Kalign query in 53.686 seconds
Traceback (most recent call last):
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/templates.py", line 536, in _extract_template_features
    seqres, chain_id, mapping_offset = _find_template_in_pdb(
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/templates.py", line 291, in _find_template_in_pdb
    raise SequenceNotInTemplateError(
alphafold.data.templates.SequenceNotInTemplateError: Could not find the template sequence in 7zcj_A. Template sequence: LPFTGLNTPNGV, chain_to_seqres: {'A': 'GSHMSNTQTVLPFTGLNTPNSGVAVDSAGTVYWVTDHGNNRVVKLAAGSNTQTVLPFTGLNTPSNGVAVDSAGTVWYVTDHGNNRVVKLAAGSNTQTVLPFTGLNTPNSGVAVDSAGTVYWVTDHGNNRVVKLAAGSNTQTVLPFTGLNTPSNGVAVDSAGTVWYVTDHGNNRVVKLAAGSNTQTVLPFTGLNTPNSGVAVDSAGTVYWVTDHGNNRVVKLAAGSNTQTVLPFTGLNTPSNGVAVDSAGTVWYVTDHGNNRVVKLAAG'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/templates.py", line 362, in _realign_pdb_template_to_query
    aligner.align([old_template_sequence, new_template_sequence]))
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/tools/kalign.py", line 98, in align
    raise RuntimeError('Kalign failed\nstdout:\n%s\n\nstderr:\n%s\n'
RuntimeError: Kalign failed
stdout:

stderr:

Kalign version 2.04, Copyright (C) 2004, 2005, 2006 Timo Lassmann

        Kalign is free software. You can redistribute it and/or modify
        it under the terms of the GNU General Public License as
        published by the Free Software Foundation.

reading from STDIN: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/templates.py", line 755, in _process_single_hit
    features, realign_warning = _extract_template_features(
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/templates.py", line 549, in _extract_template_features
    seqres, mapping = _realign_pdb_template_to_query(
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/templates.py", line 365, in _realign_pdb_template_to_query
    raise QueryToTemplateAlignError(
alphafold.data.templates.QueryToTemplateAlignError: Could not align old template LPFTGLNTPNGV to template GSHMSNTQTVLPFTGLNTPNSGVAVDSAGTVYWVTDHGNNRVVKLAAGSNTQTVLPFTGLNTPSNGVAVDSAGTVWYVTDHGNNRVVKLAAGSNTQTVLPFTGLNTPNSGVAVDSAGTVYWVTDHGNNRVVKLAAGSNTQTVLPFTGLNTPSNGVAVDSAGTVWYVTDHGNNRVVKLAAGSNTQTVLPFTGLNTPNSGVAVDSAGTVYWVTDHGNNRVVKLAAGSNTQTVLPFTGLNTPSNGVAVDSAGTVWYVTDHGNNRVVKLAAG (7zcj_A). Error: Kalign failed
stdout:

stderr:

Kalign version 2.04, Copyright (C) 2004, 2005, 2006 Timo Lassmann

        Kalign is free software. You can redistribute it and/or modify
        it under the terms of the GNU General Public License as
        published by the Free Software Foundation.

reading from STDIN: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/bin/create_individual_features.py", line 288, in <module>
    app.run(main)
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/bin/create_individual_features.py", line 280, in main
    create_and_save_monomer_objects(curr_monomer, pipeline,
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/bin/create_individual_features.py", line 215, in create_and_save_monomer_objects
    m.make_features(
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphapulldown/objects.py", line 150, in make_features
    self.feature_dict = pipeline.process(fasta_file, msa_output_dir)
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/pipeline.py", line 223, in process
    templates_result = self.template_featurizer.get_templates(
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/templates.py", line 960, in get_templates
    result = _process_single_hit(
  File "/home/thomas-ws/miniconda3/envs/AlphaPulldown/lib/python3.8/site-packages/alphafold/data/templates.py", line 786, in _process_single_hit
    error = ('%s_%s (sum_probs: %.2f, rank: %d): feature extracting errors: '
TypeError: must be real number, not NoneType

**Comment by th-of** [comment]
Solved the issue. Edited the sequence for 7zcj in pdb_seqrest.txt and changed it to the one on RCSB.
