### ISSUE TITLE
Option to run Bait as a homo-dimer?

### ISSUE THREAD

**Issue by calebmallery** [KosinskiLab/AlphaPulldown#188]
Hi there, 
I have recently completed "part 1" of a run where I computed the multiple sequence alignment for one bait (which is a homo-dimer) where my bait file looked like:
>monomer
sequence
>monomer
sequence

I am no ready to run the actual predictions and am unsure of which option to choose so that the output is my bait of interest (as a dimer) against the candidate list. Any suggustions or feedback would be greatly appreciated!

**Comment by dingquanyu** [comment]
Hi,

Thanks for your interest in our package. Sure I believe ```pulldown``` mode best matches your need. However, it may need some changes in your command.

for the ```--protein_lists``` parameter, you could set it to ```--protein_lists=bait.txt,bait.txt,candidate.txt``` then both subunits of the bait will be modelled. 

I hope this solution works for you.

Yours
DIngquan

**Comment by calebmallery** [comment]
@dingquanyu Thank you for your quick reply, I will give your suggestion a try and update you with how it goes!

**Comment by calebmallery** [comment]
This worked great, thank you very much! I do however have a separate question that does not seem to be adressed elsewhere. When attempting to use alpha-analysis.sif with the following command: 
singularity exec --no-home --bind path/to/alphapulldown_predictions_out/ ./alpha-analysis.sif run_get_good_pae.sh --output_dir=/test_csv_dir --cutoff=100

I receive the following error: 
Traceback (most recent call last):
  File "/app/alpha-analysis/get_good_inter_pae.py", line 151, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/app/alpha-analysis/get_good_inter_pae.py", line 141, in main
    pi_score_df=pd.merge(pi_score_df,other_measurements_df,on="jobs")
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 107, in merge
    op = _MergeOperation(
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 700, in __init__
    ) = self._get_merge_keys()
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 1110, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/generic.py", line 1840, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'jobs'

I am not sure how to interpret this error. I saw in a similar issue that it was recommended to increase the cutoff size which has not worked. Any help would be greatly apprecieated.
