### ISSUE TITLE
alpha-analysis.sif

### ISSUE THREAD

**Issue by calebmallery** [KosinskiLab/AlphaPulldown#199]
This tool has been excellent for generating predictions. However, I am having trouble assessing them in a high-throughput way because I cannot generate a summary table. I have downloaded the most recent version of alpha-analysis.sif and execute the following command :
singularity exec --no-home --bind /path/to/alphapulldown_predictions_out/ ./alpha-analysis.sif run_get_good_pae.sh --output_dir=/path/to/outdir

Where I receive the following output and error:
INFO:    Converting SIF file to temporary sandbox...
Traceback (most recent call last):
  File "/app/alpha-analysis/get_good_inter_pae.py", line 151, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.9/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/app/alpha-analysis/get_good_inter_pae.py", line 141, in main
    pi_score_df=pd.merge(pi_score_df,other_measurements_df,on="jobs")
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 107, in merge
    op = _MergeOperation(
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 700, in __init__
    ) = self._get_merge_keys()
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/reshape/merge.py", line 1110, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
  File "/opt/conda/lib/python3.9/site-packages/pandas/core/generic.py", line 1840, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'jobs'
INFO:    Cleaning up image...

Any help would be greatly appreciated!

**Comment by dingquanyu** [comment]
Hi,

Sorry that this error happened to you. It seems that you are using the default value of cutoff and unfortunately, none of your models may have satisfied it. Could you add ```--cutoff=100``` to the end of your command and have another try?

Yours
Dingquan

**Comment by calebmallery** [comment]
Thank you for your quick response!
Unfortunately that did not work and I am receiving the same error.

**Comment by dingquanyu** [comment]
Oh I see. In your original command, the way you mount is wrong. It should be: 
```--bind /path/to/alphapulldown_predictions_out/:/mnt``` .  I think this should resolve it plus the ```--cutoff=100``` Singularity's homepage has the detailed usage of Singularity containers if you'd like some explanations. 

Cheers,
Dingquan

**Comment by calebmallery** [comment]
That worked great! Thank you again for the suggestions.
