### ISSUE TITLE
Fresh install fails SCOPData from Bio.Data import

### ISSUE THREAD

**Issue by grandrea** [KosinskiLab/AlphaPulldown#234]
Just re-installed AlphaPulldown following README instructions, I get a fail due to new BioPython modules

```
 create_individual_features.py --fasta_paths=candidates.fasta,baits.fasta --data_dir=/data/software/dbs3 --save_msa_files=False --output_dir=/data/alphafold_runs/alphapulldown/output_data --max_template_date=2023-11-11 --skip_existing=False
 
 
Traceback (most recent call last):
  File "/data/software/anaconda3/envs/AlphaPulldown/bin/create_individual_features.py", line 7, in <module>
    from alphapulldown.objects import MonomericObject
  File "/data/software/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/alphapulldown/objects.py", line 11, in <module>
    from alphafold.data import pipeline_multimer
  File "/data/software/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/alphafold/data/pipeline_multimer.py", line 29, in <module>
    from alphafold.data import feature_processing
  File "/data/software/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/alphafold/data/feature_processing.py", line 20, in <module>
    from alphafold.data import msa_pairing
  File "/data/software/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/alphafold/data/msa_pairing.py", line 23, in <module>
    from alphafold.data import pipeline
  File "/data/software/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/alphafold/data/pipeline.py", line 23, in <module>
    from alphafold.data import templates
  File "/data/software/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/alphafold/data/templates.py", line 27, in <module>
    from alphafold.data import mmcif_parsing
  File "/data/software/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/alphafold/data/mmcif_parsing.py", line 24, in <module>
    from Bio.Data import SCOPData
ImportError: cannot import name 'SCOPData' from 'Bio.Data' (/data/graziadei/software/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/Bio/Data/__init__.py)

```

See also this issue
https://github.com/Rappsilber-Laboratory/AlphaLink2/issues/17

Fix seems to be in the recipe to force  biopython==1.81

**Comment by grandrea** [comment]
ah i see it was already mentioned and taken care of

**Comment by dingquanyu** [comment]
Hi @grandrea 

Thank you very much for the suggestion :D
