### ISSUE TITLE
No module named 'alphafold.version'

### ISSUE THREAD

**Issue by cmwilson252** [KosinskiLab/AlphaPulldown#250]
Hello, I am trying to install AlphaPulldown using the instructions on the front page:

conda create -n AlphaPulldown -c omnia -c bioconda -c conda-forge python==3.10 openmm==8.0 pdbfixer==1.9 kalign2 cctbx-base pytest importlib_metadata hhsuite

source activate AlphaPulldown
conda install -c bioconda hmmer
python3 -m pip install alphapulldown==1.0.4
pip install jax==0.4.23 jaxlib==0.4.23+cuda11.cudnn86 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

If you do this you'll get some dependency conflicts from ColabFold regarding dm-haiku, absl-py, immutabledict, and pandas. You can fix these by install ColabFold first.

However, when I am done with all these steps and just go to test APD using the commands below (from mmseqs2_manual.md):

source activate AlphaPulldown
create_individual_features.py

I get the following console output:

Traceback (most recent call last):
  File "/opt/conda/envs/AlphaPulldown/bin/create_individual_features.py", line 12, in <module>
    from alphapulldown.utils import save_meta_data, create_uniprot_runner, parse_fasta, get_run_alphafold
  File "/opt/conda/envs/AlphaPulldown/lib/python3.10/site-packages/alphapulldown/utils.py", line 9, in <module>
    from alphafold.version import __version__ as AF_VERSION
ModuleNotFoundError: No module named 'alphafold.version'

**Comment by dingquanyu** [comment]
Hi @cmwilson252 ,

I'm really sorry that this error occurred but I couldn't reproduce it even after a fresh installation in a new conda env. In our github repo and the tar files on pypi this line of import inside ```utils.py``` is ```from alphafold.version import __version__ as AF_VERSION ```like this : https://github.com/KosinskiLab/AlphaPulldown/blob/231863af7faa61fa04d45829c90a3bab9d9e2ff2/alphapulldown/utils.py#L9  I don't know why the line changed into ```from alphafold.version import version as AF_VERSION``` in your case.

Could you double check your PYTHONPATH environmental variable? I think you might have accidentally overwritten it and import alphafold from a different path. 

Hope it helps.

Yours,
Dingquan

**Comment by dingquanyu** [comment]
Hi,

Just checking if the problem is solved?

**Comment by maflister** [comment]
We have the same issue. We do not have a typo. It just doesn't work.

**Comment by dingquanyu** [comment]
Issue closed for now due to inactivity.
