### ISSUE TITLE
Use correct residue numbering in the PAE plots 

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#27]

**Comment by dingquanyu** [comment]
Hi Jan,

I think the current version of residue numbering is what the actual residue numbers in the PDB file. As in here: https://github.com/KosinskiLab/AlphaPulldown/blob/345f9182b7f4cb41106b2e5bbef3b45494a733c7/alphapulldown/plot_pae.py#L40-L42
the labels on the y axis are corresponding to the actual number of residues in each chain.

**Comment by DimaMolod** [comment]
I just tried to model with 1 region `Q8I2G6:1-30` and with 2 regions in 1 line `Q8I5K4:1-30:40-100`
For 1 region the PAE numbers are mostly correct apart from the inverse x-axis. On the plot it started from 30 and ended at 0:
![Q8I2G6_1-30_PAE_plot_ranked_0](https://github.com/user-attachments/assets/f59bb0b9-0131-48ca-9aa4-ba45db40f76e)
This probably could be fixed by adding this line
`ax1.set_xlim([min(xticks), max(xticks)])` [here](https://github.com/KosinskiLab/AlphaPulldown/blob/main/alphapulldown/utils/plotting.py#L33)

...
When I tried two regions per line (Q8I5K4:1-30:40-100), it died
(it is a different problem, but I will put the error log here):
`I0722 12:52:21.252175 140737350223680 alphafold_backend.py:304] Now running predictions on Q8I5K4_1-30_40-100. Checking existing results...
Traceback (most recent call last):
  File "/opt/conda/bin/run_structure_prediction.py", line 268, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/bin/run_structure_prediction.py", line 255, in main
    predict_structure(
  File "/opt/conda/bin/run_structure_prediction.py", line 152, in predict_structure
    for predicted_job in predicted_jobs:
  File "/opt/conda/lib/python3.10/site-packages/alphapulldown/folding_backend/alphafold_backend.py", line 435, in predict
    prediction_results = AlphaFoldBackend.predict_individual_job(
  File "/opt/conda/lib/python3.10/site-packages/alphapulldown/folding_backend/alphafold_backend.py", line 358, in predict_individual_job
    processed_feature_dict = model_runner.process_features(
  File "/opt/conda/lib/python3.10/site-packages/alphafold/model/model.py", line 131, in process_features
    return features.np_example_to_features(
  File "/opt/conda/lib/python3.10/site-packages/alphafold/model/features.py", line 96, in np_example_to_features
    tensor_dict = proteins_dataset.np_to_tensor_dict(
  File "/opt/conda/lib/python3.10/site-packages/alphafold/model/tf/proteins_dataset.py", line 165, in np_to_tensor_dict
    tensor_dict = parse_reshape_logic(tensor_dict, features_metadata)
  File "/opt/conda/lib/python3.10/site-packages/alphafold/model/tf/proteins_dataset.py", line 107, in parse_reshape_logic
    parsed_features[k] = tf.reshape(v, new_shape, name="reshape_%s" % k)
  File "/opt/conda/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/opt/conda/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 1021, in _create_c_op
    raise ValueError(e.message)
ValueError: Cannot reshape a tensor with 192192 elements to shape [192,91,22] (384384 elements) for '{{node reshape_template_aatype}} = Reshape[T=DT_FLOAT, Tsh
ape=DT_INT32](Const, reshape_template_aatype/shape)' with input shapes: [96,91,22], [3] and with input tensors computed as partial shapes: input[1] = [192,91,2
2].`
