### ISSUE TITLE
KeyError: 'template_confidence_scores'

### ISSUE THREAD

**Issue by Qrouger** [KosinskiLab/AlphaPulldown#292]
Hi, I got this issue : 

/home/emmanuel/anaconda3/envs/new_one/lib/python3.11/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
I0319 10:09:13.147184 140415475287872 utils.py:358] checking if output_dir exists /data/emmanuel/alphapulldown_result/Plasmid_F
I0319 10:09:13.147861 140415475287872 run_multimer_jobs.py:232] All pickle files have been found
I0319 10:09:13.233106 140415475287872 run_multimer_jobs.py:241] done creating multimer ArtA_and_DUF932
Traceback (most recent call last):
  File "/home/emmanuel/anaconda3/bin/run_multimer_jobs.py", line 489, in <module>
    app.run(main)
  File "/home/emmanuel/anaconda3/envs/new_one/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/emmanuel/anaconda3/envs/new_one/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/emmanuel/anaconda3/bin/run_multimer_jobs.py", line 468, in main
    multimers = create_multimer_objects(data, FLAGS.monomer_objects_dir, not FLAGS.no_pair_msa)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/anaconda3/bin/run_multimer_jobs.py", line 237, in create_multimer_objects
    multimer = MultimericObject(interactors=interactors, pair_msa=pair_msa,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/anaconda3/bin/alphapulldown/objects.py", line 456, in __init__
    self.create_all_chain_features()
  File "/home/emmanuel/anaconda3/bin/alphapulldown/objects.py", line 632, in create_all_chain_features
    self.feature_dict = self.pair_and_merge(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/anaconda3/bin/alphapulldown/objects.py", line 597, in pair_and_merge
    np_example = msa_pairing.merge_chain_features(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/anaconda3/bin/alphafold/data/msa_pairing.py", line 427, in merge_chain_features
    np_example = _merge_features_from_multiple_chains(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/anaconda3/bin/alphafold/data/msa_pairing.py", line 348, in _merge_features_from_multiple_chains
    feats = [x[feature_name] for x in chains]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/anaconda3/bin/alphafold/data/msa_pairing.py", line 348, in <listcomp>
    feats = [x[feature_name] for x in chains]
             ~^^^^^^^^^^^^^^
KeyError: 'template_confidence_scores'

After use an all_vs_all run_multimer_jobs.py script in feature create by mmseq2.
Feature looks like :
![Screenshot from 2024-03-19 10-22-24](https://github.com/KosinskiLab/AlphaPulldown/assets/144003341/94101a83-6d76-4fef-854c-c60926bff3b9)

Thanks.
Quentin

**Comment by dingquanyu** [comment]
Hi @Qrouger 

I'm really sorry that this occurred and I have pushed a new commit to the main branch fixing the mmseqs2 mode. Could you maybe pull the changes from the main branch and rerun the feature generations via mmseqs2 again and then re-run the modelling jobs? I hope it helps.

Yours
Dingquan

**Comment by Qrouger** [comment]
I had already done it, but in doubt I did it again. And I have exactly the same result.

Quentin.

**Comment by dingquanyu** [comment]
@Qrouger 

Sorry I don't know which sequence Art A you used. I used [Q18F79](https://www.uniprot.org/uniprotkb/Q18F79/entry#sequences) as DUF932 and got the pickle from mmseqs2, in which it has "template_confidence_scores". Maybe you could paste the Art A sequence you used?
```
>>> import pickle
>>> duf932 = pickle.load(open("DUF932.pkl",'rb')).feature_dict
/home/dingquanyu/.local/lib/python3.10/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
>>> duf932.get('template_confidence_scores')
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.]])
>>> 

```

**Comment by dingquanyu** [comment]
Thanks for the info and I've reproduced the error using this sequence. Will work on fixing this.

**Comment by Qrouger** [comment]
Hi, 
I try the beta version and I have a similar error with same protein.

Traceback (most recent call last):
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/run_structure_prediction.py", line 354, in <module>
    main()
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/run_structure_prediction.py", line 342, in main
    object_to_model, flags_dict, postprocess_flags, output_dir= pre_modelling_setup(interactors, args)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/run_structure_prediction.py", line 292, in pre_modelling_setup
    object_to_model = MultimericObject(
                      ^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/alphapulldown/objects.py", line 456, in __init__
    self.create_all_chain_features()
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/alphapulldown/objects.py", line 640, in create_all_chain_features
    self.feature_dict = self.pair_and_merge(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/alphapulldown/objects.py", line 605, in pair_and_merge
    np_example = msa_pairing.merge_chain_features(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/lib/python3.11/site-packages/alphafold/data/msa_pairing.py", line 427, in merge_chain_features
    np_example = _merge_features_from_multiple_chains(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/lib/python3.11/site-packages/alphafold/data/msa_pairing.py", line 348, in _merge_features_from_multiple_chains
    feats = [x[feature_name] for x in chains]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/lib/python3.11/site-packages/alphafold/data/msa_pairing.py", line 348, in <listcomp>
    feats = [x[feature_name] for x in chains]
             ~^^^^^^^^^^^^^^
KeyError: 'template_release_date'
Traceback (most recent call last):
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/run_multimer_jobs.py", line 273, in <module>
    app.run(main)
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/run_multimer_jobs.py", line 269, in main
    subprocess.run(" ".join(command), check=True, shell=True)
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 /home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/run_structure_prediction.py --output_directory /data/emmanuel/alphapulldown_result/Plasmid_F --num_cycle 3 --num_predictions_per_model 1 --data_directory /data/emmanuel/alphadata_v3 --features_directory /data/emmanuel/alphapulldown_result/Plasmid_F --fold_backend alphafold --use_ap_style  --protein_delimiter + --input ArtA+SLT' returned non-zero exit status 1.

**Comment by dingquanyu** [comment]
Hi Quentin,

Have you rerun the mmseqs2 step for this protein after installing the new version? 

Yours
Dingquan

**Comment by Qrouger** [comment]
Yes, all of features have been done with new version.

**Comment by dingquanyu** [comment]
Hi Quentin,

I realised that when a sequence is queried with AlphaFold MSA alignments, it does not contain the features like template_release_date but when using mmseqs2, it will return such features. Therefore, you will get this key error if you are using 2 feature pickles, in which one of them was generated by AlphaFold pipeline and the other one was done through mmseq2. I will make these 2 compatible in the future release.  

Yours
Dingquan

**Comment by Qrouger** [comment]
Hi,
If I understand, set --use_mmseqs2 on True make that you can have two different way to generate feature pickle ? mmseq2 or AlphaFold pipeline.
This agrees with my files : 
      SLT_env get templates_101 directory
      ArtA_env dont have this directory

Thanks,
Quentin

**Comment by dingquanyu** [comment]
You should have both a SLT_env and ArtA_env directory as --use_mmseqs2 flag will switch to mmseqs2 mode and never runs the AlphaFold pipeline.

**Comment by Qrouger** [comment]
Yes I got both because I run mmseqs2 for all proteins, but ArtA_env don't have templates_101 directory. That the only difference.
![Screenshot from 2024-04-30 13-28-08](https://github.com/KosinskiLab/AlphaPulldown/assets/144003341/18b0d6ae-d7bb-4331-9ef4-97ec7cee7642)

**Comment by dingquanyu** [comment]
Thanks for the update! It showed that template_release_date is the only missing one here. I will fix this incompatibility soon.
