### ISSUE TITLE
How to run with reduced_dbs

### ISSUE THREAD

**Issue by fteufel** [KosinskiLab/AlphaPulldown#293]
Hi,

thank you for making this package available!

I wanted to run AF with reduced dbs. My understanding is that I can do that by setting `--db_preset=reduced_dbs`

However, I get an error that it tries to open the bfd database:
```
I0319 14:53:19.990841 139928686040896 templates.py:857] Using precomputed obsolete pdbs weights/pdb_mmcif/obsolete.dat.
Traceback (most recent call last):
  File "/nfs_home/users/fegt/.conda/envs/AlphaPulldown/bin/create_individual_features.py", line 252, in <module>
    app.run(main)
  File "/nfs_home/users/fegt/.conda/envs/AlphaPulldown/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/nfs_home/users/fegt/.conda/envs/AlphaPulldown/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/nfs_home/users/fegt/.conda/envs/AlphaPulldown/bin/create_individual_features.py", line 244, in main
    create_and_save_monomer_objects(curr_monomer, pipeline,
  File "/nfs_home/users/fegt/.conda/envs/AlphaPulldown/bin/create_individual_features.py", line 181, in create_and_save_monomer_objects
    save_meta_data(flags_dict, meta_data_outfile)
  File "/nfs_home/users/fegt/.conda/envs/AlphaPulldown/lib/python3.10/site-packages/alphapulldown/utils.py", line 535, in save_meta_data
    metadata["databases"].update(get_metadata_for_database(k, v))
  File "/nfs_home/users/fegt/.conda/envs/AlphaPulldown/lib/python3.10/site-packages/alphapulldown/utils.py", line 471, in get_metadata_for_database
    hash_value = get_hash(fn)
  File "/nfs_home/users/fegt/.conda/envs/AlphaPulldown/lib/python3.10/site-packages/alphapulldown/utils.py", line 435, in get_hash
    with open(filename, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'weights/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_hhm.ffindex'
```

Command, basically from the tutorial + the additional flag
```
create_individual_features.py \
  --fasta_paths=data/test_batch.fasta \
  --data_dir=weights \
  --save_msa_files=True \
  --output_dir=features \
  --use_precomputed_msas=False \
  --max_template_date=2050-01-01 \
  --skip_existing=True \
  --db_preset=reduced_dbs \
  --seq_index=$SLURM_ARRAY_TASK_ID
```

Is there an additional flag that I need to set?
Thanks!

**Comment by Qrouger** [comment]
Hi @fteufel,
In my case reduced_dbs work with the additional flag.
Do you have only the reduce database on your directory weights ?

Quentin.

**Comment by fteufel** [comment]
Hi @Qrouger, that's exactly the case - I don't have the full database, but AlphaPulldown wants to save metadata for it anyway. I just hardcoded the full db to be skipped from the metadata logging for now, but that wouldn't be a very elegant PR.
