### ISSUE TITLE
operands could not be broadcast together with shapes - MMSEQ2

### ISSUE THREAD

**Issue by rukibuki** [KosinskiLab/AlphaPulldown#319]
I have been running ~550 alphapulldown runs  durign the last week, without any major problems.  But then suddenly today I got hit by the "operands could not be broadcast together with shapes" error constnatly (see complete error below). I have read issue [233](https://github.com/KosinskiLab/AlphaPulldown/issues/233) and other issues related to the same error, and it seems MMSEQ2 might be the problem if I udnerstand the other issues correctly.
I exclusively use MMSEQ2 for the MSA runs, and have done so for all of the 550 pulldowns. So if it is related to MMSEQ2 I don't understand why it suddenly kicked in now, out of nowhere. I have not changed a thing in the setup.

I should say we are on an older version of AlphaPullDown (date of APD files are March 21 2023) but it has been working fine up to today.

Has anything been updated that might break the use of MMSEQ2 in APD or is it something else?

Thanks for all of your hard work on this git Dingquan Yu!

Error:
Traceback (most recent call last):
  File "/opt/bioxray/programs/anaconda3/envs/alphapulldown/AlphaPulldown/alphapulldown/run_multimer_jobs.py", line 372, in <module>
    app.run(main)
  File "/opt/bioxray/programs/anaconda3/envs/alphapulldown/lib/python3.8/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/bioxray/programs/anaconda3/envs/alphapulldown/lib/python3.8/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/bioxray/programs/anaconda3/envs/alphapulldown/AlphaPulldown/alphapulldown/run_multimer_jobs.py", line 342, in main
    multimers = create_multimer_objects(data, FLAGS.monomer_objects_dir, not FLAGS.no_pair_msa)
  File "/opt/bioxray/programs/anaconda3/envs/alphapulldown/AlphaPulldown/alphapulldown/run_multimer_jobs.py", line 177, in create_multimer_objects
    multimer = MultimericObject(interactors=interactors,pair_msa=pair_msa)
  File "/opt/bioxray/programs/anaconda3/envs/alphapulldown/lib/python3.8/site-packages/alphapulldown/objects.py", line 456, in __init__
    self.create_all_chain_features()
  File "/opt/bioxray/programs/anaconda3/envs/alphapulldown/lib/python3.8/site-packages/alphapulldown/objects.py", line 534, in create_all_chain_features
    self.feature_dict = self.pair_and_merge(
  File "/opt/bioxray/programs/anaconda3/envs/alphapulldown/lib/python3.8/site-packages/alphapulldown/objects.py", line 508, in pair_and_merge
    np_example = feature_processing.process_final(np_example)
  File "/opt/bioxray/programs/anaconda3/envs/alphapulldown/lib/python3.8/site-packages/alphafold/data/feature_processing.py", line 167, in process_final
    np_example = _make_msa_mask(np_example)
  File "/opt/bioxray/programs/anaconda3/envs/alphapulldown/lib/python3.8/site-packages/alphafold/data/feature_processing.py", line 191, in _make_msa_mask
    np_example['msa_mask'] *= seq_mask[None]
ValueError: operands could not be broadcast together with shapes (4095,1320) (1,2280) (4095,1320)

**Comment by dingquanyu** [comment]
> I @rukibuki, normally you just have to pull the new AlphaPulldown git version to use mmseq2 feature while waiting for a new version inpip. I think this problem is just proteins dependant.
> 
> edit: You can try this version, it should work. pip install alphapulldown==2.0.0b2
> 
> https://github.com/KosinskiLab/AlphaPulldown/releases/tag/2.0.0b2
> 
> Quentin.

Thanks for your help @Qrouger ! Quentin is correct and the current beta version has the fix of this problem in it. Just I'm afraid you have to rerun your feature creations using the mmseqs2 in the latest beta version again to get correct feature matrices.

Yours
Dingquan
