### ISSUE TITLE
Too many proteins in one interaction ?

### ISSUE THREAD

**Issue by Qrouger** [KosinskiLab/AlphaPulldown#337]
Hi, recently I buy lot of memory to do bigger structure interactions, and I have the impression Alpha Pulldown cannot take more than 10 proteins (here 20). Maybe it's cause the name is too long ?

Traceback (most recent call last):
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/run_structure_prediction.py", line 354, in <module>
    main()
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/run_structure_prediction.py", line 342, in main
    object_to_model, flags_dict, postprocess_flags, output_dir= pre_modelling_setup(interactors, args)
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/run_structure_prediction.py", line 332, in pre_modelling_setup
    makedirs(output_dir, exist_ok=True)
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 36] File name too long: '/data/emmanuel/alphapulldown_result/construction_R388/VirB6_TrwI_and_VirB6_TrwI_and_VirB6_TrwI_and_VirB6_TrwI_and_VirB6_TrwI_and_VirB2_TrwL_and_VirB2_TrwL_and_VirB2_TrwL_and_VirB2_TrwL_and_VirB2_TrwL_and_VirB2_TrwL_and_VirB2_TrwL_and_VirB2_TrwL_and_VirB2_TrwL_and_VirB2_TrwL_and_VirB2_TrwL_and_VirB2_TrwL_and_VirB2_TrwL_and_VirB2_TrwL_and_VirB2_TrwL'
Traceback (most recent call last):
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/run_multimer_jobs.py", line 273, in <module>
    app.run(main)
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/run_multimer_jobs.py", line 269, in main
    subprocess.run(" ".join(command), check=True, shell=True)
  File "/home/emmanuel/anaconda3/envs/Alpha_multimer2/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 /home/emmanuel/anaconda3/envs/Alpha_multimer2/bin/run_structure_prediction.py --output_directory /data/emmanuel/alphapulldown_result/construction_R388 --num_cycle 3 --num_predictions_per_model 1 --data_directory /data/emmanuel/alphadata_v3 --features_directory /data/emmanuel/alphapulldown_result/R388_feature_data --fold_backend alphafold --use_ap_style  --protein_delimiter + --input VirB6_TrwI+VirB6_TrwI+VirB6_TrwI+VirB6_TrwI+VirB6_TrwI+VirB2_TrwL+VirB2_TrwL+VirB2_TrwL+VirB2_TrwL+VirB2_TrwL+VirB2_TrwL+VirB2_TrwL+VirB2_TrwL+VirB2_TrwL+VirB2_TrwL+VirB2_TrwL+VirB2_TrwL+VirB2_TrwL+VirB2_TrwL+VirB2_TrwL' returned non-zero exit status 1.

It's not an error out of memory.

Thanks.
Quentin

**Comment by yummy-hat** [comment]
Try giving the proteins shorter names? Your output is showing that the directory name is just too long: `OSError: [Errno 36] File name too long:`.

**Comment by Qrouger** [comment]
Hey @yummy-hat, Yes that's what I finally did, but it's not easy to read
But it's maybe interesting to detected same proteins in custom mode, and write a name like : "5_prot1_and_7_prot2"

Quentin.
