### ISSUE TITLE
jackhammer error running test

### ISSUE THREAD

**Issue by Clockris** [KosinskiLab/AlphaPulldown#350]
Hi,

I am trying to run alphapulldown2.0.0b2 on an example case as follows:
```python .../AlphaPulldown/alphapulldown/scripts/create_individual_features.py \
--fasta_paths=.../downloads/example_1_sequences/output/bait/baits.fasta,.../downloads/example_1_sequences/output/db/example_1_sequences.fasta \
  --data_dir=.../alphapulldown_db \
  --save_msa_files=False \
  --output_dir=.../my_output \
  --use_precomputed_msas=False \
  --max_template_date=2043-04-05 \
  --skip_existing=True \
  --seq_index=1
```

but in a few seconds it fails generating the following error:

```
.../lib/python3.10/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.                                                   
  warnings.warn(                                                                                                                                                         
2024-05-29 16:07:24.846827: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin c
uDNN when one has already been registered                                                                                                                                
2024-05-29 16:07:24.847002: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cu
FFT when one has already been registered                                                                                                                                 
2024-05-29 16:07:24.848618: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin
 cuBLAS when one has already been registered                                                                                                                             
I0529 16:07:28.513200 139904458721088 create_individual_features.py:181] Will use hmmsearch looking for templates                                                        
I0529 16:07:29.566886 139904458721088 templates.py:858] Using precomputed obsolete pdbs .../AlphaPulldown/alphapulldown_db/pdb_mmcif/obsolete.dat.
I0529 16:07:30.250202 139904458721088 objects.py:144] will save msa files in :.../mpalma_t35753_install-and-run-AlphaPulldown/my_output/sp_P78344_IF4G2_HUMAN_Eukaryotic_translation_initiation_factor_4_gamma_2_OS_Homo_sapiens_OX_9606_GN_EIF4G2_PE_1_SV_1
Traceback (most recent call last):
  File ".../AlphaPulldown/alphapulldown/scripts/create_individual_features.py", line 372, in <module>
    app.run(main)
  File ".../lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File ".../lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File ".../AlphaPulldown/alphapulldown/scripts/create_individual_features.py", line 363, in main
    process_sequences_individual_mode()
  File ".../AlphaPulldown/alphapulldown/scripts/create_individual_features.py", line 293, in process_sequences_individual_mode
    create_and_save_monomer_objects(curr_monomer, pipeline)
  File ".../AlphaPulldown/alphapulldown/scripts/create_individual_features.py", line 242, in create_and_save_monomer_objects
    monomer.make_features(
  File ".../lib/python3.10/site-packages/alphapulldown/objects.py", line 148, in make_features
    self.feature_dict = pipeline.process(
  File ".../lib/python3.10/site-packages/alphafold/data/pipeline.py", line 163, in process
    jackhmmer_uniref90_result = run_msa_tool(
  File ".../lib/python3.10/site-packages/alphafold/data/pipeline.py", line 94, in run_msa_tool
    result = msa_runner.query(input_fasta_path, max_sto_sequences)[0]  # pytype: disable=wrong-arg-count
  File ".../lib/python3.10/site-packages/alphafold/data/tools/jackhmmer.py", line 170, in query
    return self.query_multiple([input_fasta_path], max_sequences)[0]
  File ".../lib/python3.10/site-packages/alphafold/data/tools/jackhmmer.py", line 181, in query_multiple
    single_chunk_results.append([self._query_chunk(
  File ".../lib/python3.10/site-packages/alphafold/data/tools/jackhmmer.py", line 133, in _query_chunk
    logging.info('Launching subprocess "%s"', ' '.join(cmd))
TypeError: sequence item 0: expected str instance, NoneType found
```

Do you have any idea of what is causing this issue and how to solve it?

Thanks,

Cristiano

**Comment by Qrouger** [comment]
Hi @Clockris, this issue looks like you have a problems with your fasta files. You can check if the two path to fasta files are correct and if files are correctly write in fasta format.

Quentin

**Comment by Clockris** [comment]
Thanks, apparently the problem was that I did not install the HMMER. I solved directly through conda "conda install bioconda::hmmer".
