### ISSUE TITLE
jax error when create_notebook.py is run

### ISSUE THREAD

**Issue by BismahGhafoor** [KosinskiLab/AlphaPulldown#381]
I am trying to make the jupyter notebook but the script is failing to open the .pkl files.

This is the error I am getting:

(base) [bg171@alice-login01 FinalProject]$ python3 test5.py
I0716 10:35:35.385460 23456246728512 test5.py:126] now processing Q09472_and_P57682
Traceback (most recent call last):
File "/lustre/alice3/scratch/alice/b/bg171/FinalProject/test5.py", line 159, in
app.run(main)
File "/home/b/bg171/miniconda3/lib/python3.12/site-packages/absl/app.py", line 308, in run
_run_main(main, args)
File "/home/b/bg171/miniconda3/lib/python3.12/site-packages/absl/app.py", line 254, in _run_main
sys.exit(main(argv))
^^^^^^^^^^
File "/lustre/alice3/scratch/alice/b/bg171/FinalProject/test5.py", line 139, in main
pae_mtx, iptm_score = obtain_pae_and_iptm(result_subdir=result_subdir,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/lustre/alice3/scratch/alice/b/bg171/FinalProject/test5.py", line 50, in obtain_pae_and_iptm
data = pickle.load(f)
^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'jax._src.device_array'

I am using jax and jaxlib versions 0.4.21.

some guidance would be appreciated a lot.

**Comment by dingquanyu** [comment]
Hi @BismahGhafoor

It seems only jax.0.4.23 works with this import. Could you try installing jax0.4.23 ?

Yours
Dingquan

**Comment by BismahGhafoor** [comment]
Hi @dingquanyu  I still got the same error even with jax 0.4.23

**Comment by dingquanyu** [comment]
Sorry I really have no idea how to solve this then. For me everything above 0.4.23 reported this error. Could you create an issue under the Jax or jaxlib repo? I'm sure there are many more discussions there.

**Comment by dingquanyu** [comment]
Meanwhile I will convert this to a discussion and hope there's someone else who solved this issue.
