### ISSUE TITLE
jackhmmer fails to run

### ISSUE THREAD

**Issue by kdneuro** [KosinskiLab/AlphaPulldown#41]
Hi, I'm trying to run pulldown for the first time and I am unable to get the example to work. It seems like an issue with alphafold's jackhmmer script but I'm not sure how to debug. Thanks!

```
(AlphaPulldown) kduong@glycine:~/AlphaPulldown$ python3 alphapulldown/create_individual_features.py --fasta_paths=example_data/example_1_sequences_shorter.fasta --data_dir=/home/kduong/af2_databases/ --save_msa_files=False --output_dir=/home/kduong/pulldown_input_output/output/ --use_precomputed_msas=False --max_template_date=2050-01-01
2022-08-24 15:53:43.371134: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
I0824 15:53:45.712832 140448664971072 templates.py:857] Using precomputed obsolete pdbs /home/kduong/af2_databases/pdb_mmcif/obsolete.dat.
I0824 15:53:45.718152 140448664971072 objects.py:112] You have chosen not to save msa output files
Traceback (most recent call last):
  File "alphapulldown/create_individual_features.py", line 247, in <module>
    app.run(main)
  File "/home/kduong/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/kduong/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "alphapulldown/create_individual_features.py", line 240, in main
    create_and_save_monomer_objects(curr_monomer, pipeline, flags_dict)
  File "alphapulldown/create_individual_features.py", line 204, in create_and_save_monomer_objects
    save_msa=FLAGS.save_msa_files,
  File "/home/kduong/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/alphapulldown/objects.py", line 118, in make_features
    input_fasta_path=fasta_file, msa_output_dir=tmpdirname
  File "/home/kduong/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/data/pipeline.py", line 169, in process
    max_sto_sequences=self.uniref_max_hits)
  File "/home/kduong/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/data/pipeline.py", line 94, in run_msa_tool
    result = msa_runner.query(input_fasta_path, max_sto_sequences)[0]  # pytype: disable=wrong-arg-count
  File "/home/kduong/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/data/tools/jackhmmer.py", line 172, in query
    input_fasta_path, self.database_path, max_sequences)
  File "/home/kduong/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/data/tools/jackhmmer.py", line 133, in _query_chunk
    logging.info('Launching subprocess "%s"', ' '.join(cmd))
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by henrywotton** [comment]
Hi,

This error simply complains that jackhammer cannot be found under your $PATH i.e. jackhammer hasn't been installed or it isn't available under your default $PATH. Unfortunately, I guess you have to install/reinstall jackhammer make sure the programme is accessible under $PATH environment variable. 

Best,
Dingquan

**Comment by kdneuro** [comment]
Thanks! Installing jackhammer in the conda environment worked!
