### ISSUE TITLE
PI score calculation failed

### ISSUE THREAD

**Issue by ewysocka** [KosinskiLab/AlphaPulldown#417]
Hello,

I am using the sif file and the script `run_get_good_pae.sh` for downstream analysis to generate the table `predictions_with_good_interpae.csv`. While I managed to produce the table, I noticed several column values were missing. The affected columns are:

```
Num_intf_residues
Polar
Hydrophobic
Charged
contact_pairs
sc
hb
sb
int_solv_en
int_area
pi_score
```

Here is the command I'm running:
```

singularity exec \
            --no-home \
            --bind </path/to/ALPHAFOLD/output_dir>:/mnt \
            </path/to>/alpha-analysis_jax_0.4.sif \
            run_get_good_pae.sh \
            --output_dir=/mnt \
            --cutoff=10
```

Here is a fragment of the stdout that I thought it's relevant:
```
/bin/chmod: changing permissions of '/app/run_get_good_pae.sh': Read-only file system
/bin/chmod: changing permissions of '/app/run_execute_notebook.sh': Read-only file system
/bin/chmod: changing permissions of '/app/run_pi_score.sh': Read-only file system
/bin/chmod: changing permissions of '/app/alpha-analysis/get_good_inter_pae.py': Read-only file system
┌──────────────────────────────────────────────────────────────────────────────┐
│                                 PyRosetta-4                                  │
│              Created in JHU by Sergey Lyskov and PyRosetta Team              │
│              (C) Copyright Rosetta Commons Member Institutions               │
│                                                                              │
│ NOTE: USE OF PyRosetta FOR COMMERCIAL PURPOSES REQUIRE PURCHASE OF A LICENSE │
│         See LICENSE.PyRosetta.md or email license@uw.edu for details         │
└──────────────────────────────────────────────────────────────────────────────┘
PyRosetta-4 2024 [Rosetta PyRosetta4.Release.python39.linux 2024.15+release.d972b59c530a12affcbe0eb4a24eedc3ce7d5060 2024-04-02T17:06:29] retrieved from: http://www.pyrosetta.org
core.init: Checking for fconfig files in pwd and ./rosetta/flags 
core.init: Rosetta version: PyRosetta4.Release.python39.linux r377 2024.15+release.d972b59 d972b59c530a12affcbe0eb4a24eedc3ce7d5060 http://www.pyrosetta.org 2024-04-02T17:06:29
core.init: Rosetta extras: []
core.init: command: PyRosetta -ex1 -ex2aro -database /opt/conda/lib/python3.9/site-packages/pyrosetta/database
basic.random.init_random_generator: 'RNG device' seed mode, using '/dev/urandom', seed=-863518226 seed_offset=0 real_seed=-863518226
basic.random.init_random_generator: RandomGenerator:init: Normal mode, seed=-863518226 RG_type=mt19937
I1011 15:38:16.037423 123722645558080 get_good_inter_pae.py:120] now processing Q9H7M9.pkl
W1011 15:38:16.037679 123722645558080 get_good_inter_pae.py:162] Q9H7M9.pkl does not have ranking_debug.json. Skipped.
I1011 15:38:16.037778 123722645558080 get_good_inter_pae.py:166] done for Q9H7M9.pkl 1 out of 71 finished.
I1011 15:38:16.037858 123722645558080 get_good_inter_pae.py:120] now processing P78536.pkl
W1011 15:38:16.037957 123722645558080 get_good_inter_pae.py:162] P78536.pkl does not have ranking_debug.json. Skipped.
I1011 15:38:16.038032 123722645558080 get_good_inter_pae.py:166] done for P78536.pkl 2 out of 71 finished.
I1011 15:38:16.038104 123722645558080 get_good_inter_pae.py:120] now processing B2RVW2_and_Q96G97
Successfully parsed plddt values
I1011 15:38:17.129545 123722645558080 get_good_inter_pae.py:166] done for B2RVW2_and_Q96G97 3 out of 71 finished.
I1011 15:38:17.129787 123722645558080 get_good_inter_pae.py:120] now processing Q9UMX0.pkl
W1011 15:38:17.129897 123722645558080 get_good_inter_pae.py:162] Q9UMX0.pkl does not have ranking_debug.json. Skipped.
I1011 15:38:17.129943 123722645558080 get_good_inter_pae.py:166] done for Q9UMX0.pkl 4 out of 71 finished.
I1011 15:38:17.129982 123722645558080 get_good_inter_pae.py:120] now processing Q9UJ14_feature_metadata_2024-08-26.json
W1011 15:38:17.130032 123722645558080 get_good_inter_pae.py:162] Q9UJ14_feature_metadata_2024-08-26.json does not have ranking_debug.json. Skipped.
I1011 15:38:17.130070 123722645558080 get_good_inter_pae.py:166] done for Q9UJ14_feature_metadata_2024-08-26.json 5 out of 71 finished.
I1011 15:38:17.130108 123722645558080 get_good_inter_pae.py:120] now processing B2RVW2_and_O95292
Successfully parsed plddt values
E1011 15:38:23.365341 123722645558080 pdb_analyser.py:173] PI score calculation failed: Command '['/bin/bash', '-c', 'source activate pi_score && export PYTHONPATH=/software:$PYTHONPATH && python /software/pi_score/run_piscore_wc.py -p /mnt/B2RVW2_and_O95292/ranked_0.pdb -o /mnt/pi_score_outputs/B2RVW2_and_O95292 -s 2 -ps 10']' returned non-zero exit status 1.. Command: ['/bin/bash', '-c', 'source activate pi_score && export PYTHONPATH=/software:$PYTHONPATH && python /software/pi_score/run_piscore_wc.py -p /mnt/B2RVW2_and_O95292/ranked_0.pdb -o /mnt/pi_score_outputs/B2RVW2_and_O95292 -s 2 -ps 10']. Error: Traceback (most recent call last):
  File "/software/pi_score/run_piscore_wc.py", line 242, in <module>
    main()
  File "/software/pi_score/run_piscore_wc.py", line 77, in main
    out = open(args.results,'w')
IOError: [Errno 22] invalid mode ('w') or filename: '/mnt/pi_score_outputs/B2RVW2_and_O95292/pi_score_10.11.24_15:38.txt'

W1011 15:38:23.369324 123722645558080 pdb_analyser.py:192] Skipping interface due to unexpected format: None
E1011 15:38:23.369582 123722645558080 pdb_analyser.py:319] An unexpected error occurred while merging the PI score data: local variable 'pi_score_files' referenced before assignment
W1011 15:38:23.369838 123722645558080 pdb_analyser.py:192] Skipping interface due to unexpected format: None
core.chemical.GlobalResidueTypeSet: Finished initializing fa_standard residue type set.  Created 985 residue types
core.chemical.GlobalResidueTypeSet: Total time to initialize 1.61502 seconds.
core.import_pose.import_pose: File '/tmp/tmp0asi7cii.pdb' automatically determined to be of type PDB
```

Best,
Emilia

**Comment by DimaMolod** [comment]
Hi @ewysocka and thank you for using AlphaPulldown.
We recently removed CCP4 from the docker analysis container. If you want to keep using it, you will have to download it and build a new container following [these instructions](https://github.com/KosinskiLab/AlphaPulldown?tab=readme-ov-file#03-installation-for-the-downstream-analysis-tools)
please let me know if this helps.
Cheers
Dima

**Comment by ewysocka** [comment]
Hi @DimaMolod,
Ok. Thanks for your help!
Cheers,
Emilia

**Comment by ewysocka** [comment]
Hi @DimaMolod,

Could you explain why CCP4 was removed?

Thanks,
Emilia

**Comment by DimaMolod** [comment]
Hi @ewysocka ,
let's say, for the jurisdictional reasons :-)
