### ISSUE TITLE
Some candidates in the prediction step lead to the following error :

### ISSUE THREAD

**Issue by ThisIsIt42** [KosinskiLab/AlphaPulldown#427]
Traceback (most recent call last):
  File "/opt/conda/bin/run_structure_prediction.py", line 274, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/bin/run_structure_prediction.py", line 258, in main
    object_to_model, flags_dict, postprocess_flags, output_dir = pre_modelling_setup(interactors, FLAGS, output_dir = FLAGS.output_directory[index])
  File "/opt/conda/bin/run_structure_prediction.py", line 184, in pre_modelling_setup
    object_to_model = MultimericObject(
  File "/opt/conda/lib/python3.10/site-packages/alphapulldown/objects.py", line 475, in __init__
    self.create_all_chain_features()
  File "/opt/conda/lib/python3.10/site-packages/alphapulldown/objects.py", line 660, in create_all_chain_features
    self.feature_dict = self.pair_and_merge(
  File "/opt/conda/lib/python3.10/site-packages/alphapulldown/objects.py", line 630, in pair_and_merge
    np_example = feature_processing.process_final(np_example)
  File "/opt/conda/lib/python3.10/site-packages/alphafold/data/feature_processing.py", line 167, in process_final
    np_example = _make_msa_mask(np_example)
  File "/opt/conda/lib/python3.10/site-packages/alphafold/data/feature_processing.py", line 191, in _make_msa_mask
    np_example['msa_mask'] *= seq_mask[None]
ValueError: operands could not be broadcast together with shapes (4095,154) (1,200) (4095,154)
Traceback (most recent call last):
  File "/opt/conda/bin/run_multimer_jobs.py", line 145, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/opt/conda/bin/run_multimer_jobs.py", line 141, in main
    subprocess.run(" ".join(command), check=True, shell=True)
  File "/opt/conda/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 /opt/conda/bin/run_structure_prediction.py --output_directory ./outputdir --num_cycle 3 --num_predictions_per_model 1 --data_directory /db --features_directory msas --pair_msa  --nomsa_depth_scan  --nomultimeric_template  --fold_backend alphafold --nocompress_result_pickles  --noremove_result_pickles  --use_ap_style  --use_gpu_relax  --protein_delimiter + --models_to_relax None --input swrD+flgB' returned non-zero exit status 1.

**Comment by DimaMolod** [comment]
Hi @ThisIsIt42 ,
I think this may happen when you mix features generated by mmseqs2 and hmmer. 
Is it the case for you? If yes, please consider re-calculating all features either using mmseqs or hmmer.
Please let me know if this helps :)

**Comment by jkosinski** [comment]
It's not because of that "+" sign in the command?

**Comment by DimaMolod** [comment]
> line 87, in parse_fold
>raise FileNotFoundError(
>FileNotFoundError: {'flgE'} not found in ['msas']

this line literally means that you don't have `flgE.pkl` file in your folder with features called `msas`.
Could you check that you have all features files calculated for these 33 problematic candidates?
