### ISSUE TITLE
Installation from pip not functional for predictions?

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#448]
When installing from pip and running run_multimer_jobs.py, I am getting the following error:
```
AttributeError: module 'ml_dtypes' has no attribute 'float8_e4m3b11'. Did you mean: 'float8_e4m3'?
Traceback (most recent call last):
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/bin/run_structure_prediction.py", line 274, in <module>
    app.run(main)
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/bin/run_structure_prediction.py", line 261, in main
    predict_structure(
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/bin/run_structure_prediction.py", line 147, in predict_structure
    model_runners_and_configs = backend.setup(**model_flags)
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/alphapulldown/folding_backend/alphafold_backend.py", line 173, in setup
    from alphafold.model import data, model
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/alphafold/model/model.py", line 20, in <module>
    from alphafold.model import features
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/alphafold/model/features.py", line 19, in <module>
    from alphafold.model.tf import input_pipeline
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/alphafold/model/tf/input_pipeline.py", line 17, in <module>
    from alphafold.model.tf import data_transforms
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/alphafold/model/tf/data_transforms.py", line 18, in <module>
    from alphafold.model.tf import shape_helpers
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/alphafold/model/tf/shape_helpers.py", line 16, in <module>
    import tensorflow.compat.v1 as tf
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python.saved_model import saved_model
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/tensorflow/python/saved_model/saved_model.py", line 20, in <module>
    from tensorflow.python.saved_model import builder
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/tensorflow/python/saved_model/builder.py", line 23, in <module>
    from tensorflow.python.saved_model.builder_impl import _SavedModelBuilder
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/tensorflow/python/saved_model/builder_impl.py", line 26, in <module>
    from tensorflow.python.framework import dtypes
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/tensorflow/python/framework/dtypes.py", line 39, in <module>
    _np_float8_e5m2 = pywrap_ml_dtypes.float8_e5m2()
TypeError: Unable to convert function return value to a Python type! The signature was
	() -> handle
Traceback (most recent call last):
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 145, in <module>
    app.run(main)
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 141, in main
    subprocess.run(" ".join(command), check=True, shell=True)
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 /g/kosinski/kosinski/software/envs/AlphaPulldown/bin/run_structure_prediction.py --output_directory /scratch/kosinski/IntegrativeCourse2024/AlphaPulldown --num_cycle 3 --num_predictions_per_model 1 --data_directory /scratch/AlphaFold_DBs/2.3.2/ --features_directory /g/alphafold/input_features/Saccharomyces_cerevisiae --pair_msa  --nomsa_depth_scan  --nomultimeric_template  --fold_backend alphafold --nocompress_result_pickles  --noremove_result_pickles  --use_ap_style  --use_gpu_relax  --protein_delimiter + --models_to_relax None --input P32349+P32910+P17890' returned non-zero exit status 1.
```

I think this is related to the error during installation, which you can also see in Github actions log:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.14.0 requires ml-dtypes==0.2.0, but you have ml-dtypes 0.5.0 which is incompatible.
```
The `ml-dtypes` gets upgraded to `0.5.0` by this command:
https://github.com/KosinskiLab/AlphaPulldown/blob/a282ff8fbb03d8bbaf7fbf5cf1c90e7718942fb9/README.md?plain=1#L452

Note that we do not see the crash in github tests, as we do not test for structure prediction there.

If I downgrade to `0.2.0`
```
pip install --upgrade ml_dtypes==0.2.0
```
the program runs but on CPU.

Is it a bug or I do sth wrong again?

**Comment by gabrielpan147** [comment]
Hello, 
I met this issue as well. I tried to upgrade tensorflow to 2.16.1 but it still does not work. No I just downgrade the package to 2.0.0.b5.

**Comment by jkosinski** [comment]
We will fix it, this is a never-ending story with dependencies breaking with updates. Do you mean you got it fixed by downgrading tensorflow to 2.0.0.b5 ?

**Comment by DimaMolod** [comment]
Hi all, could you please try again with v2.0.0 and confirm it works now?

**Comment by jkosinski** [comment]
Works for me, thanks!
