### ISSUE TITLE
snakemake from main branch crashes on prediction

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#449]
I am getting the following error:
```
Activating singularity image /g/kosinski/kosinski/IntegrativeCourse2024/AlphaPulldown/AlphaPulldownSnakemake/.snakemake/singularity/b1a0408b77e6fc0b904c69cd981fb35c.simg
Traceback (most recent call last):
  File "/opt/conda/bin/run_structure_prediction.py", line 8, in <module>
    sys.exit(run_structure_prediction())
  File "/opt/conda/lib/python3.10/site-packages/alphapulldown/entry_points.py", line 13, in run_structure_prediction
    from alphapulldown.scripts import run_structure_prediction
  File "/opt/conda/lib/python3.10/site-packages/alphapulldown/scripts/run_structure_prediction.py", line 16, in <module>
    from alphapulldown.folding_backend import backend
  File "/opt/conda/lib/python3.10/site-packages/alphapulldown/folding_backend/__init__.py", line 11, in <module>
    from .alphafold_backend import AlphaFoldBackend
  File "/opt/conda/lib/python3.10/site-packages/alphapulldown/folding_backend/alphafold_backend.py", line 21, in <module>
    from alphapulldown.objects import MultimericObject, MonomericObject, ChoppedObject
  File "/opt/conda/lib/python3.10/site-packages/alphapulldown/objects.py", line 12, in <module>
    from alphafold.data.tools import jackhmmer
ModuleNotFoundError: No module named 'alphafold.data'
```
when running snakemake with branch main. It is probably caused by this commit: https://github.com/KosinskiLab/AlphaPulldown/commit/8bf958090de3a650e2332ecdbdb9bfcd8035894c ?

**Comment by DimaMolod** [comment]
Fixed in 385e72bb2010d740424b3ed3b5a6921ee413497b
