### ISSUE TITLE
run_multimer_jobs.py "check_empty_templates error"

### ISSUE THREAD

**Issue by Prospero912** [KosinskiLab/AlphaPulldown#453]
Hello,
I'm quite new in AlphaPulldown and AlphaFold and trying to run everything from the beginning till the end on a few test sequences:

I've finished successfully the first part of the analysis with "colabfold_batch" because I do not have access to the full alpha fold databases right now.

But when I run run_multimer_jobs.py I have following output with error:

run_multimer_jobs.py --mode=pulldown --monomer_objects_dir=alpha_pulldown/projects/out_dir --data_dir=alpha_pulldown/alphafoldDB --protein_lists=alpha_pulldown/projects/baits.txt,alpha_pulldown/projects/candidates_shorter.txt --output_path=alpha_pulldown/projects/output/prediction --num_cycle=3 --num_predictions_per_model=1 --job_index=1

/home/mikhailt/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/Bio/Data/SCOPData.py:18: BiopythonDeprecationWarning: The 'Bio.Data.SCOPData' module will be deprecated in a future release of Biopython in favor of 'Bio.Data.PDBData.
  warnings.warn(
2024-11-06 09:11:12.574316: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1730913072.636023     520 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1730913072.650994     520 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
I1106 09:11:16.184099 140681742997312 utils.py:271] checking if output_dir exists alpha_pulldown/projects/output/prediction
I1106 09:11:16.186321 140681742997312 run_multimer_jobs.py:229] All pickle files have been found
Traceback (most recent call last):
  File "/home/mikhailt/anaconda3/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 462, in <module>
    app.run(main)
  File "/home/mikhailt/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/mikhailt/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/mikhailt/anaconda3/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 433, in main
    multimers = create_multimer_objects(data, FLAGS.monomer_objects_dir, not FLAGS.no_pair_msa)
  File "/home/mikhailt/anaconda3/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 233, in create_multimer_objects
    interactors = create_interactors(data, monomer_objects_dir, job_idx)
  File "/home/mikhailt/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/alphapulldown/utils.py", line 245, in create_interactors
    monomer = load_monomer_objects(monomer_dir_dict, curr_interactor_name)
  File "/home/mikhailt/anaconda3/envs/AlphaPulldown/lib/python3.10/site-packages/alphapulldown/utils.py", line 151, in load_monomer_objects
    if check_empty_templates(monomer.feature_dict):
AttributeError: 'tuple' object has no attribute 'feature_dict'

Can you please give me advice here?

Best,
Mikhail

**Comment by DimaMolod** [comment]
Hello Mikhail, may I ask which version of AlphaPulldown do you use?

**Comment by Prospero912** [comment]
My bad, I accidentally installed one of the previous alphapulldown versions with some older CUDA libraries and now it is fine.
Thank you very much for pushing into the right direction!

Best,
Mikhail
