### ISSUE TITLE
Error when running SLURM array job — TypeError: all_seq_msa_features() got an unexpected keyword argument 'msa_output_dir' 

### ISSUE THREAD

**Issue by harshstava** [KosinskiLab/AlphaPulldown#47]
Hello — when running through the first step of the example 1 md notebook inside a SLURM array, I'm running into the following issue: 

```
Traceback (most recent call last):
  File "/scratch/user/AlphaPulldown1/bin/create_individual_features.py", line 247, in <module>
    app.run(main)
  File "/scratch/user/AlphaPulldown1/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/scratch/user/AlphaPulldown1/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/scratch/user/AlphaPulldown1/bin/create_individual_features.py", line 240, in main
    create_and_save_monomer_objects(curr_monomer, pipeline, flags_dict)
  File "/scratch/user/AlphaPulldown1/bin/create_individual_features.py", line 204, in create_and_save_monomer_objects
    save_msa=FLAGS.save_msa_files,
  File "/scratch/user/AlphaPulldown1/lib/python3.7/site-packages/alphapulldown/objects.py", line 135, in make_features
    save_msa=False,use_precomuted_msa=False)
  File "/scratch/user/AlphaPulldown1/lib/python3.7/site-packages/alphapulldown/objects.py", line 116, in execute_pipeline
    use_precomuted_msa=use_precomuted_msa,
TypeError: all_seq_msa_features() got an unexpected keyword argument 'msa_output_dir'
```

The following command that I'm using inside my bash script is as follows: 

```
[create_individual_features.py --fasta_paths=/scratch/user/AlphaPulldownTest/baits.fasta,\
/scratch/user/AlphaPulldownTest/sequences_shorter.fasta --data_dir=/vast/user/public/alphafold --save_msa_files=False \
--output_dir=/scratch/user/AlphaPulldownMSAOut --use_precomputed_msas=False --max_template_date=2050-01-01 --skip_existing=False \
--seq_index=$SLURM_ARRAY_TASK_ID]

```

I've tried a couple of configs for the settings, although have gotten no success. A little unsure what is meant by "msa_output_dir" in the error message. Many thanks beforehand!

**Comment by henrywotton** [comment]
Hi,

I'm really sorry I guess you might have installed AlphaPulldown version 0.21.7 or 0.21.8? It turned out the new versions are not stable and I have removed them. Could you please `pip unistall alphapulldown` and roll back to 0.21.6 by `pip install alphapulldown==0.21.6`?

Cheers

**Comment by harshstava** [comment]
Yes, that seems to be the issue. Thanks! 

`alphapulldown           0.21.7`

**Comment by henrywotton** [comment]
No problem. Could you let us know if rolling back to 0.21.6 worked fine with you in the rest of workflow as well?
