### ISSUE TITLE
Installing the project as a package in developer mode

### ISSUE THREAD

**Issue by swanss** [KosinskiLab/AlphaPulldown#52]
Hi,

I'd like to test out some changes and additional arguments to the scripts in this repo. I made a fork of the repo, made some changes to the code, and then tried to install the repo as a package so I could verify that the changes worked. I tried making a very simple `setup.py` file and then installing it as package into my conda environment with `pip install -e .`. I tried testing the package by running the unaltered code, but I got an odd error (will attach for reference at the bottom of this message), which I suspect is due to an alphafold version mismatch. 

What is the easiest way for me to install my forked repo in the same way as the official AlphaPulldown package? Is there a setup.py or other file that I could use to ensure that it's installed in the same way?

In case it's informative, here's the error
```Traceback (most recent call last):
 File "/home/gridsan/sswanson/miniconda3/envs/AlphaPulldown/bin/run_multimer_jobs.py", line 7, in <module>
 exec(compile(f.read(), __file__, 'exec'))
 File "/home/gridsan/sswanson/local_code_mirror/AlphaPulldown/alphapulldown/run_multimer_jobs.py", line 333, in <module>
 app.run(main)
 File "/home/gridsan/sswanson/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 308, in run
 _run_main(main, args)
 File "/home/gridsan/sswanson/miniconda3/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 254, in _run_main
 sys.exit(main(argv))
 File "/home/gridsan/sswanson/local_code_mirror/AlphaPulldown/alphapulldown/run_multimer_jobs.py", line 329, in main
 predict_multimers(multimers)
 File "/home/gridsan/sswanson/local_code_mirror/AlphaPulldown/alphapulldown/run_multimer_jobs.py", line 279, in predict_multimers
 random_seed=random_seed,
 File "/home/gridsan/sswanson/local_code_mirror/AlphaPulldown/alphapulldown/run_multimer_jobs.py", line 252, in predict_individual_jobs
 seqs=multimer_object.input_seqs,
 File "/home/gridsan/sswanson/local_code_mirror/AlphaPulldown/alphapulldown/predict_structure.py", line 62, in predict
 prediction_result.update({"seqs": seqs})
AttributeError: 'tuple' object has no attribute 'update'```

**Comment by swanss** [comment]
I realized that I can download the source code for the package directly from https://pypi.org/. I now see that the alphafold code is provided directly with the package within the `src` directory.

**Comment by jkosinski** [comment]
Hi,

Thanks for contributing! Wouldn't cloning this repo and overwriting the
pypi version with export PYTHONPATH work?

Best,
Jan

**Comment by swanss** [comment]
Hi Jan,

Thanks for the tip, that is much simpler than what I was doing.

Cheers,
Sebastian

**Comment by jkosinski** [comment]
Cool, and we would be happy to consider your contributions in a pull
request once you're ready.

Best,
Jan
