### ISSUE TITLE
Improve auto-creating output directory in create_individual_features.py

### ISSUE THREAD

**Issue by jkosinski** [KosinskiLab/AlphaPulldown#71]
```create_individual_features.py``` has this nice feature of auto-creating output directory when not present by:

```
Path(FLAGS.output_dir).mkdir(parents=True, exist_ok=True)
```

However, when running a job array with many jobs in parallel, it happens that several jobs that started in the same time detect that the folder is missing and then try to create it. But, because only one of them manages to do that, the others crash because the folder has been created in the meantime:
```
Traceback (most recent call last):
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.7/pathlib.py", line 1230, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/kosinski/output/test_data/features'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.7/pathlib.py", line 1230, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/kosinski/output/test_data'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/bin/create_individual_features.py", line 267, in <module>
    app.run(main)
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/bin/create_individual_features.py", line 226, in main
    Path(FLAGS.output_dir).mkdir(parents=True, exist_ok=True)
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.7/pathlib.py", line 1234, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.7/pathlib.py", line 1234, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/g/kosinski/kosinski/software/envs/AlphaPulldown/lib/python3.7/pathlib.py", line 1230, in mkdir
    self._accessor.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/scratch/kosinski/output'
```
Could this exception be somehow handled by simply proceeding with script execution in case of FileExistsError?

**Comment by jkosinski** [comment]
This should only catch FileExistsError, maybe like this:
```
try: 
    Path(FLAGS.output_dir).mkdir(parents=True, exist_ok=True)
except FileExistsError:
    logging.info(f"{FLAGS.output_dir} exists.")
```

**Comment by DimaMolod** [comment]
shall we close this as completed?

**Comment by jkosinski** [comment]
I think so! So closing it.
