### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'hhsearch': 'hhsearch'

### ISSUE THREAD

**Issue by sarahemooneyy** [KosinskiLab/AlphaPulldown#89]
Hi,

I've been having problems getting create_individual_features.py to work for a while now. I haven't had issues in the past, but recently it's been giving me this error: 

2022-12-07 12:53:39.148417: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
I1207 12:53:45.021706 140651954386752 create_individual_features.py:200] You are using the new version
I1207 12:53:45.027969 140651954386752 create_individual_features.py:222] running mmseq now
I1207 12:53:45.028071 140651954386752 objects.py:197] You chose to calculate MSA with mmseq2
I1207 12:53:45.028564 140651954386752 objects.py:206] looking for possible precomputed a3m at /n/scratch3/users/s/sm738/desmond_pulldown_objects/Pectobacterium_pa
rmentieri_RNS08_42_1A_CdnB_AGS_C.a3m
I1207 12:53:45.028648 140651954386752 objects.py:208] input is /n/scratch3/users/s/sm738/desmond_pulldown_objects/Pectobacterium_parmentieri_RNS08_42_1A_CdnB_AGS_
C.a3m
COMPLETE: 100%|██████████| 150/150 [elapsed: 00:01 remaining: 00:00]
I1207 12:53:47.511983 140651954386752 objects.py:248] will search for templates in local template database
I1207 12:53:48.131940 140651954386752 hhsearch.py:85] Launching subprocess "hhsearch -i /tmp/tmp1spwfwf6/query.a3m -o /tmp/tmp1spwfwf6/output.hhr -maxseq 1000000 
-d /n/shared_db/alphafold/pdb70/pdb70"
Traceback (most recent call last):
  File "/home/sm738/.conda/envs/AlphaPulldown/bin/create_individual_features.py", line 286, in <module>
    app.run(main)
  File "/home/sm738/.conda/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/sm738/.conda/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/sm738/.conda/envs/AlphaPulldown/bin/create_individual_features.py", line 279, in main
    flags_dict,use_mmseqs2=FLAGS.use_mmseqs2)
  File "/home/sm738/.conda/envs/AlphaPulldown/bin/create_individual_features.py", line 227, in create_and_save_monomer_objects
    output_dir=FLAGS.output_dir)
  File "/home/sm738/.conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphapulldown/objects.py", line 250, in make_mmseq_features
    pdb70_database_path,template_mmcif_dir,query_sequence=self.sequence,max_template_date=max_template_date)]
  File "/home/sm738/.conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphapulldown/objects.py", line 181, in mk_template
    hhsearch_result = hhsearch_pdb70_runner.query(a3m_lines)
  File "/home/sm738/.conda/envs/AlphaPulldown/lib/python3.7/site-packages/alphafold/data/tools/hhsearch.py", line 87, in query
    cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/home/sm738/.conda/envs/AlphaPulldown/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/home/sm738/.conda/envs/AlphaPulldown/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hhsearch': 'hhsearch'

I haven't been able to solve the issue on my own so I was wondering if there is anything you can do to help!

Here is my script as well:

create_individual_features.py \
--fasta_paths=desmond_baits.fasta,desmond_candidates.fasta \
--data_dir=/n/shared_db/alphafold/ \
--output_dir=/n/scratch3/users/s/sm738/desmond_pulldown_objects \
--skip_existing=True \
--use_mmseqs2=True \
--max_template_date=2050-01-01 \
--seq_index=$SLURM_ARRAY_TASK_ID

Thanks in advance!

**Comment by henrywotton** [comment]
Hi,

That's simply because you haven't installed or loaded HHSuite. You could check with your IT to see if they have built the HHSuite as a module or you can install HHSuite as shown in our installation guide by running ```conda install -c bioconda hmmer hhsuite``` within the same conda env you created.

Hope it helps.

Cheers

**Comment by sarahemooneyy** [comment]
Oh thank you! I recently re-installed the package and forgot to install HHSuite!! Thanks!
