### ISSUE TITLE
output_dir is merged with protein description?

### ISSUE THREAD

**Issue by DimaMolod** [KosinskiLab/AlphaPulldown#90]
when I try to create features for my fasta file at /scratch/dima/AP/lucas/P22137.fasta I get this error:

`(AlphaPulldown) [dmolodenskiy@login01 lucas]$ create_individual_features.py --fasta_paths=P22137.fasta --data_dir=/scratch/AlphaFold_DBs/ --save_msa_files=False --output_dir=. --use_precomputed_msas=False --max_template_date=2050-01-01 --skip_existing=False
2022-12-08 10:28:54.080451: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
I1208 10:29:08.847636 139885265946432 templates.py:857] Using precomputed obsolete pdbs /scratch/AlphaFold_DBs/pdb_mmcif/obsolete.dat.
Traceback (most recent call last):
  File "/home/dmolodenskiy/.conda/envs/AlphaPulldown/bin/create_individual_features.py", line 247, in <module>
    app.run(main)
  File "/home/dmolodenskiy/.conda/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/dmolodenskiy/.conda/envs/AlphaPulldown/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/dmolodenskiy/.conda/envs/AlphaPulldown/bin/create_individual_features.py", line 240, in main
    create_and_save_monomer_objects(curr_monomer, pipeline, flags_dict)
  File "/home/dmolodenskiy/.conda/envs/AlphaPulldown/bin/create_individual_features.py", line 198, in create_and_save_monomer_objects
    with output_meta_file(metadata_output_path) as meta_data_outfile:
  File "/home/dmolodenskiy/.conda/envs/AlphaPulldown/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/dmolodenskiy/.conda/envs/AlphaPulldown/bin/create_individual_features.py", line 33, in output_meta_file
    with open(file_path, "w") as outfile:
FileNotFoundError: [Errno 2] No such file or directory: './sp|P22137|CLH_YEAST Clathrin heavy chain OS=Saccharomyces cerevisiae (strain ATCC 204508 / S288c) OX=559292 GN=CHC1 PE=1 SV=1_feature_metadata_2022-12-08.txt'`

**Comment by henrywotton** [comment]
Ah it's actually because there are too many special characters like "(" "=" and space in your input file. The output_dir is not merged with the description but rather the meta file's file name is merged with it. Could you maybe just use the uniprot id as the description then rerun the command?

**Comment by DimaMolod** [comment]
Sure I can shorten the description, but it would still be nice if AP works with original FASTA files from UniProt. I didn't look into the code but maybe use smth like `from Bio import SeqIO` to parse the description?

**Comment by jkosinski** [comment]
Note also the renaming script:
https://github.com/KosinskiLab/AlphaPulldown/blob/main/alphapulldown/prepare_seq_names.py,
which will convert UniProt names to UniProt ids in a multi-sequence fasta
file.

Long complicated names are not good as later on, AlphaPulldown generates
job and folder names like proteinA_protein_B_proteinC, which could get
pretty long and complex. I find renaming to simple names (UniProt ids or
names) the most convenient.

**Comment by DimaMolod** [comment]
ok, then at least show some sane exception message, or (better) do the change automatically and let the user know that the description will be shortened. Otherwise nobody apart from us will be able to ever use AP - imagine: you download a fast file from UniProt (naturally) and try to run AP and get this crazy message at the very first stage. Would you want to figure out what was wrong with your file or you simply delete the repo and find something that actually works?..

**Comment by henrywotton** [comment]
That's a really good suggestion. Maybe some validation steps should be added before running anything.
