### ISSUE TITLE
AlphaPulldown 0.22.3 can't run with Alphafold database in Version 2.3.0

### ISSUE THREAD

**Issue by lorethan22** [KosinskiLab/AlphaPulldown#98]
The new Alphafold 2.3.0 database does not match AlphaPulldown 0.22.3 anymore or viceversa. Alphafold updates the AlphaFold-Multimer model parameters in /params from Version 2 to 3 and the uniclust30 database was replaced with uniref30. 
So I can't using 
create_individual_features.py --fasta_paths=baits.fasta,example_1_sequences_shorter.fasta --data_dir=/data/a/alphafold_db --save_msa_files=True --output_dir=/data/a/***/apd --use_precomputed_msas=False --max_template_date=2023-01-01  --skip_existing=False
2023-01-12 14:57:46.326993: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
I0112 14:58:30.538307 22510983153472 templates.py:857] Using precomputed obsolete pdbs /data/a/alphafold_db/pdb_mmcif/obsolete.dat.
E0112 14:58:30.547909 22510983153472 hhblits.py:82] Could not find HHBlits database /data/a/alphafold_db/uniclust30/uniclust30_2018_08/uniclust30_2018_08
Traceback (most recent call last):
  File "/data/a/anaconda3/envs/AlphaPulldown0.22.3/bin/create_individual_features.py", line 286, in <module>
    app.run(main)
  File "/data/a/anaconda3/envs/AlphaPulldown0.22.3/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/data/a/anaconda3/envs/AlphaPulldown0.22.3/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/data/a/anaconda3/envs/AlphaPulldown0.22.3/bin/create_individual_features.py", line 252, in main
    pipeline = create_pipeline()
  File "/data/a/anaconda3/envs/AlphaPulldown0.22.3/bin/create_individual_features.py", line 188, in create_pipeline
    release_dates_path=None,
  File "/data/a/anaconda3/envs/AlphaPulldown0.22.3/lib/python3.7/site-packages/alphafold/data/pipeline.py", line 140, in __init__
    databases=[bfd_database_path, uniclust30_database_path])
  File "/data/a/anaconda3/envs/AlphaPulldown0.22.3/lib/python3.7/site-packages/alphafold/data/tools/hhblits.py", line 83, in __init__
    raise ValueError(f'Could not find HHBlits database {database_path}')
ValueError: Could not find HHBlits database /data/a/alphafold_db/uniclust30/uniclust30_2018_08/uniclust30_2018_08

anymore and run_multimer_jobs.py are looking for params_model_1_multimer_v2.npz which were replaced with /params_model_1_multimer_v3.npz

Will Alphapulldown be adapted to the new Alphafold database?

**Comment by henrywotton** [comment]
Hi,

Actually I've already pushed a branch that allows AlphaPulldown to run the AlphaFold 2.3.0. You can find the new installation instructions here: https://github.com/KosinskiLab/AlphaPulldown/tree/alphafold-2.3.0
I strongly recommend creating a new conda env for this installation.

Sorry since the codes are still testing, I haven't released a formal version yet but based on our testing so far, the code on  that branch works fine. Please feel free to try it and let us know if there's any issue.

Cheers

**Comment by tcoates5** [comment]
Any update on the code testing, or still WIP?

**Comment by henrywotton** [comment]
Hi @tcoates5 ,

Sorry since some users still are using the previous version of AlphaFold databases instead of version 2.3.0, we decided to keep the codes on the 2.3.0 branch for now. Please check out the other branch and the programmes works fine if you create a brand new conda env and install that version of the programme. 

Cheers
